name: letstest
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  cloud_firestore: ^5.0.2
  firebase_auth: ^5.1.1
  shared_preferences: ^2.2.3
  random_string: ^2.3.1
  firebase_core: ^3.1.1


  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/images/
    - asset/images/logo.png

