// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHqDERxzGxtZgYyn8TzTcbSDZYrFZOM_k',
    appId: '1:34860945701:web:b58e2876a2461142798acc',
    messagingSenderId: '34860945701',
    projectId: 'letstest-5da90',
    authDomain: 'letstest-5da90.firebaseapp.com',
    storageBucket: 'letstest-5da90.appspot.com',
    measurementId: 'G-R76GF9BG70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWFR85oize5UiuiZj9sEA7V6LUoOscNQ4',
    appId: '1:34860945701:android:d23f6e1fd0a20128798acc',
    messagingSenderId: '34860945701',
    projectId: 'letstest-5da90',
    storageBucket: 'letstest-5da90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEET9SUGvZQW5yWcWkeRrhxI5pFOqfpWo',
    appId: '1:34860945701:ios:e614aa775024c3d5798acc',
    messagingSenderId: '34860945701',
    projectId: 'letstest-5da90',
    storageBucket: 'letstest-5da90.appspot.com',
    iosBundleId: 'com.example.letstest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEET9SUGvZQW5yWcWkeRrhxI5pFOqfpWo',
    appId: '1:34860945701:ios:e614aa775024c3d5798acc',
    messagingSenderId: '34860945701',
    projectId: 'letstest-5da90',
    storageBucket: 'letstest-5da90.appspot.com',
    iosBundleId: 'com.example.letstest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHqDERxzGxtZgYyn8TzTcbSDZYrFZOM_k',
    appId: '1:34860945701:web:e03669157bdf4910798acc',
    messagingSenderId: '34860945701',
    projectId: 'letstest-5da90',
    authDomain: 'letstest-5da90.firebaseapp.com',
    storageBucket: 'letstest-5da90.appspot.com',
    measurementId: 'G-Y8XQ049LP2',
  );
}
